# Generated by Django 4.2.3 on 2023-07-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boathistory',
            options={'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.AddField(
            model_name='boat',
            name='price',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Цена'),
        ),
    ]
