# Generated by Django 4.2.3 on 2023-07-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0002_alter_boathistory_options_boat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
